### ISSUE TITLE
Feature Request: `required` attribute.

### ISSUE THREAD

**Issue by Lucasmiguelmac** [kamalkech/svelte-formly#1]
Hello there. First and foremost, great job with this library. Each day I discover some new cool stuff about it.

I was wondering if it was possible to create the possibility to pass the `"required"` (boolean) inside the attributes field:
```json
{
        "type": "input",
        "name": "my-field",
        "attributes": {
            "type": "text",
            "label": "Some field",
            "placeholder": "Some placeholder",
            "required": true, // -> This
        },
    },
```
I tried it today and couldn't make it work.

**Comment by kamalkech** [comment]
- Thank u for using the package, to post comments / issues should go to [https://github.com/arabdevelop/svelte-formly](https://github.com/arabdevelop/svelte-formly)
- To make field required, should check documentation, so you need to use rules array ```rules: ['required']```
